academy/urls.py
from django.contrib import admin
from django.urls import path, include
from academy.views import _class, _section, _session, api_attendance, api_section_last_session, api_section_create

app_name = "attendance"
urlpatterns = [
    path('', _class,name='classes'),
    path('<course>/<section>/', _section,name='sections'),
    path('<course>/<section>/<session>', _session,name='section'),
    path('api/<course>/<section>/<session>/<student_id>/<status>', api_attendance),
    path('api/<course>/<section>/query_last_session', api_section_last_session),
    path('api/<course>/<section>/create', api_section_create),
]

mysite/mysite/urls.py
from django.conf import settings

from django.conf.urls.static import static
from django.urls import include, path
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = [
    path("", TemplateView.as_view(template_name="homepage.html"), name="home"),
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

untitled/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('attendance/', include('academy.urls', namespace='attendance')),
    path('account/', include('accountviews.urls')),
]

templates/class/class_attendance.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Table V01</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {#    <!--Import Google Icon Font-->#}
    {#    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">#}
    {#    <link rel="stylesheet" href="{% static 'css/class_section.css' %}">#}
    {#    <!-- Compiled and minified CSS -->#}
    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">#}

    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!--===============================================================================================-->
    <style>
        .container-table100 {
            background: -webkit-linear-gradient(45deg, {{ color1 }}, {{ color2 }});
            background: -o-linear-gradient(45deg, {{ color1 }}, {{ color2 }});
            background: -moz-linear-gradient(45deg, {{ color1 }}, {{ color2 }});
            background: linear-gradient(45deg, {{ color1 }}, {{ color2 }});
        }

    </style>
</head>
<body>


<div class="limiter">
    <div class="container-table100">
        <div class="wrap-table100">
            <div class="table100">
                <table>
                    <thead>
                    <tr class="table100-head">
                        <th class="column1">Student</th>
                        <th class="column2">Status</th>
                        <th class="column3">Notes</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for student in all_students.all %}
                        <tr id="{{ student.id }}">
                            <td class="column1" id="{{ student.id }}-name">{{ student }}</td>
                            <td class="column2" id="{{ student.id }}-status" onclick="change_status({{ student.id }})">
                                Click to Change
                            </td>
                            <td class="column3" id="{{ student.id }}-notes">{{ student.notes }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<!--===============================================================================================-->
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'js/main.js' %}"></script>
<!--===============================================================================================-->
{% for attendance in attendances %}
    <script>
        var id = "{{ attendance.student.id }}";
        var element = document.getElementById(id).children[1];
        {% if attendance.status == "present" %}
            element.innerHTML = "<span style='color:green;'>Present &#x2714;</span>";
        {% elif attendance.status == "absent"  %}
            element.innerHTML = "<span style='color:red;'>Absent &#x2716;</span>";
        {% endif %}
    </script>
{% endfor %}
<!--===============================================================================================-->
<script>
    function change_status(id) {
        var current_status = 0;
        var element = document.getElementById(id + "-status");
        var to_send = "";
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                var response = this.responseText;
                if (response.includes("present saved")) {
                    element.innerHTML = "<span style='color:green;'>Present &#x2714;</span>"
                }
                else if (response.includes("absent saved")) {
                    element.innerHTML = "<span style='color:red;'>Absent &#x2716;</span>"
                }
                else {
                    alert("Something went wrong, Please try again...");
                    console.log(response)
                }

            }
        };

        if (element.innerHTML.includes("Absent")) {
            current_status = -1;
            to_send = "present";
        }
        else if (element.innerHTML.includes("Present")) {
            current_status = 1;
            to_send = "absent";
        }
        else {
            current_status = 0;
            to_send = "present";
        }


        xhttp.open("GET", "http://localhost:8000/attendance/api/{{ course }}/{{ section }}/{{ session }}/" + id + "/" + to_send, true);
        xhttp.send();

    }
</script>

</body>
</html>

templates/class/class_root.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html>
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/class_section.css' %}">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <style>

        {% for class in classes %}
            .card-color{{ class.id }} {
            background: #c850c0;
            background: -webkit-linear-gradient(45deg, {{ class.color1 }}, {{ class.color2 }});
            background: -o-linear-gradient(45deg, {{ class.color1 }}, {{ class.color2 }});
            background: -moz-linear-gradient(45deg, {{ class.color1 }}, {{ class.color2 }});
            background: linear-gradient(45deg, {{ class.color1 }}, {{ class.color2 }});
        }
        {% endfor %}

    </style>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>

<nav>
    <div class="nav-wrapper">
        <a href="#!" class="brand-logo hide-on-med-and-down center">MyCademy</a>

        <div class="container col s0">
            <a href="#!" class="breadcrumb">Classes</a>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row section">
        {% if classes %}
            {% for class in classes %}
                <div class="col s12 m4">
                    <div class="card card-color{{ class.id }}">
                        <div class="card-content white-text">
                            <span class="card-title">{{ class }}</span>
                            <p>
                                {{ class.course.school }}
                            </p>
                            <p>
                                {{ class.students.count }} Students
                            </p>
                        </div>
                        <div class="card-action card-color{{ class.id }}">
                            <a href="{{ class.course }}/{{ class.section }}">Go to sessions</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h4 class="center-align">
                Create your first session
                <p>
                    <a class="modal-trigger waves-effect waves-light btn-large" href="#modal1">Create</a>
                </p>

            </h4>
        {% endif %}
    </div>
    {% if sessions %}
        <a class="modal-trigger btn-floating btn-large waves-effect waves-light red" href="#modal1"><i
                class="material-icons">add</i></a>
    {% endif %}

</div>


<!-- Modal Structure -->
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h4>Create a new session?</h4>
    </div>
    <div class="modal-footer">
        <a href="#!" onclick="create_new_session()" class="modal-close waves-effect waves-green btn-flat">Yes</a>
    </div>
</div>


<!-- Compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    $(document).ready(function () {
        $('.modal').modal();
    });

    $("create_new_session").onclick = create_new_session;

    function create_new_session() {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                var response = this.responseText;
                if (response.includes("created"))
                    location.reload()
            }
        }
        xhttp.open("GET", "http://localhost:8000/attendance/api/{{ course }}/{{ section }}/create", true);
        xhttp.send();
    }
</script>
</body>
</html>


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Courses</title>#}
{#</head>#}
{#<body>#}
{##}
{#{% for class in classes %}#}
{#    <p><a href="{{ class.course.course_name }}/{{ class.section }}">{{ class }}</a></p>#}
{#{% endfor %}#}
{#</body>#}
{#</html>#}

templates/class/class_section.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html>
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/class_section.css' %}">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <style>

        .card-color {
            background: #c850c0;
            background: -webkit-linear-gradient(45deg, {{ color1 }}, {{ color2 }});
            background: -o-linear-gradient(45deg, {{ color1 }}, {{ color2 }});
            background: -moz-linear-gradient(45deg, {{ color1 }}, {{ color2 }});
            background: linear-gradient(45deg, {{ color1 }}, {{ color2 }});
        }
    </style>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>

<nav>
    <div class="nav-wrapper">
        <a href="#!" class="brand-logo hide-on-med-and-down center">MyCademy</a>

        <div class="container col s0">
            <a href="{% url 'attendance:classes' %}" class="breadcrumb">Classes</a>
            <a href="#!" class="breadcrumb">Sessions</a>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row section">
        {% if sessions %}
            {% for session in sessions %}
                <div class="col s12 m4">
                    <div class="card card-color">
                        <div class="card-content white-text">
                            <span class="card-title">Session {{ session.session_nember }}</span>
                            <p>
                                {{ session.class_name }}
                            </p>

                            <p>
                                {{ session.start_datetime|localtime|date:"M, 21" }}
                            </p>

                        </div>
                        <div class="card-action card-color">
                            <a href="{% url 'attendance:section' course section session.id %}">Go to attendance list</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h4 class="center-align">
                Create your first session
                <p>
                    <a class="modal-trigger waves-effect waves-light btn-large" href="#modal1">Create</a>
                </p>

            </h4>
        {% endif %}
    </div>
    {% if sessions %}
        <a class="modal-trigger btn-floating btn-large waves-effect waves-light red" href="#modal1"><i
                class="material-icons">add</i></a>
    {% endif %}

</div>


<!-- Modal Structure -->
<div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h4>Create a new session?</h4>
    </div>
    <div class="modal-footer">
        <a href="#!" onclick="create_new_session()" class="modal-close waves-effect waves-green btn-flat">Yes</a>
    </div>
</div>


<!-- Compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script>
    $(document).ready(function () {
        $('.modal').modal();
    });

    $("create_new_session").onclick = create_new_session;

    function create_new_session() {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                var response = this.responseText;
                if (response.includes("created"))
                    location.reload()
            }
        }
        xhttp.open("GET", "http://localhost:8000/attendance/api/{{ course }}/{{ section }}/create", true);
        xhttp.send();
    }
</script>
</body>
</html>